---

- name: Create web root folder
  file: path=/var/html state=directory mode=0777

- name: Configure nginx webserver in Ubuntu
  when: ansible_distribution == "Ubuntu"
  copy: src=default dest=/etc/nginx/sites-available/default
  notify:
      - Restart nginx web server

- name: Configure nginx webserver in Centos 
  when: ansible_distribution == "CentOS"
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify:
      - Restart nginx web server
